# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 05:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=70)),
                ('time', models.TimeField(auto_now=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=70)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='login.User')),
                ('want', models.ManyToManyField(related_name='wanted_by', to='login.User')),
            ],
            managers=[
                ('appointmentManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
